### Variáveis
@baseUrl = http://localhost:3000

### 1. CREATE COLUMN
POST {{baseUrl}}/column
Content-Type: application/json

{
  "name": "Concluído"
}

### 2. FIND ALL COLUMN
GET {{baseUrl}}/column


### 3. REORDER COLUMN
POST {{baseUrl}}/column/reorder
Content-Type: application/json

### 4. DELETE COLUMN
DELETE {{baseUrl}}/column/:id

### 5. CREATE CARD
POST {{baseUrl}}/card
Content-Type: application/json

{
  "name": "Card 3",
  "description": "Descrição do Card 3",
  "columnId": 1
}
